# -*- coding: utf-8 -*-
"""Colab_Google_Fish_Detection_YOLOv8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hICK3CeRh19YTDGV6DSxxZKEVFzr_1eP

### Mount Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

ROOT_DIR = '/content/drive/MyDrive/TrainYOLOv8CustomDataset'

import locale
locale.getpreferredencoding = lambda: "UTF-8"

"""# Install YOLOv8:"""

# Pip install (recommended)
!pip install ultralytics

"""## **Train model**"""

import os

from ultralytics import YOLO
# Load a model
model = YOLO('yolov8n.yaml') # load pre trained model
# Use the model
results = model.train(data=os.path.join(ROOT_DIR,'data1.yaml'), epochs=105,batch=15)

"""# Inferencing"""

!yolo task=detect mode=predict model=/content/drive/MyDrive/runs/detect/train/Weights/best.pt conf=0.25 source=/content/drive/MyDrive/TrainYOLOv8CustomDataset/data/images/Videos_Test